### ISSUE TITLE
TypeError: '<' not supported between instances of 'memoryview' and 'memoryview'

### ISSUE THREAD

**Issue by binarydad** [modoboa/modoboa#2410] opened 2021-11-23 18:02 UTC
# Impacted versions

* OS Type: Debian/Ubuntu
* OS Version: 20.04
* Database Type: not sure
* Database version: X.y
* Modoboa: 1.17.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

It appears to be part of the following CRON job:

```
# Quarantine cleanup
0       0       *       *       *       root    $PYTHON $INSTANCE/manage.py qcleanup
```
# Current behavior

In a daily email, I get the following error:

```
Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 21, in <module>
    main()
  File "/srv/modoboa/instance/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/lib/python3.8/site-packages/modoboa_amavis/management/commands/qcleanup.py", line 59, in handle
    Msgs.objects.filter(time_num__lt=limit).delete()
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/db/models/query.py", line 711, in delete
    deleted, _rows_count = collector.delete()
  File "/srv/modoboa/env/lib/python3.8/site-packages/django/db/models/deletion.py", line 266, in delete
    self.data[model] = sorted(instances, key=attrgetter("pk"))
TypeError: '<' not supported between instances of 'memoryview' and 'memoryview'
```
Not sure how to proceed. The install is pretty vanilla. Thank you!

**Comment by tonioo** [comment] 2021-11-30 16:36
Duplicate of https://github.com/modoboa/modoboa-amavis/issues/115

**Closed by tonioo** 2021-11-30 16:36 UTC
