### ISSUE TITLE
CSS ISSUE

### ISSUE THREAD

**Issue by DamonNomadJr** [modoboa/modoboa#1804] opened 2019-12-08 16:20 UTC
# Impacted versions

* Modoboa: 1.19
* installer used: Yes
* Webserver: Nginx/Apache

# Steps to reproduce
1. Go to webmail
2. Bring up the left side menu to open up compose
3. Compose is spawned/opens as z-index behind the top menu and is not clickable

# Video/Screenshot link (optional)

![](https://i.ibb.co/z8mFt4x/Screenshot-20191208-111458-2.png)

**Comment by tonioo** [comment] 2020-01-06 09:05
Duplicate of https://github.com/modoboa/modoboa-webmail/issues/155.

**Closed by tonioo** 2020-01-06 09:05 UTC
