### ISSUE TITLE
Command check_mx incorrect behavior

### ISSUE THREAD

**Issue by Toniob** [modoboa/modoboa#1335] opened 2017-12-21 10:55 UTC
Currently, the subcommand check_mx is used to check mx (duh !) but also dnsbl.
On my instance of modoboa, dnsbl checks are fine only for the first 6 domains, the 16 others are in a warning state, with a message like "no information available".

By running the task with print statements, I've got a lot of gaierror exceptions
[Errno -2] Name or service not known
[Errno -3] Temporary failure in name resolution

It seems that the check is runned for every domains. As dnsbl works with ip addresses, it shouldn't. The blacklist should only be checked one time per ip address and the result put in the database for this ip (and not for the domain).

It will be a big performance enhancement, which is probably causing my issue.

**Comment by fyfe** [comment] 2018-01-03 18:20
`[Errno -2] Name or service not known`  means the IP being checked isn't listed, this is good you don't want to be listed.

`[Errno -3] Temporary failure in name resolution` some DNSBL impose rate limits to stop you querying their database too much, it's probably caused by repeatedly querying the same IP address over a short period of time.

I've added a fix for this to #1339 which also adds support for IPv6 addresses.

**Closed** 2018-01-05 10:59 UTC
