### ISSUE TITLE
Non-ASCII chars in password

### ISSUE THREAD

**Issue by GreenItSolutions** [modoboa/modoboa#1230] opened 2017-09-13 08:48 UTC
Hi,
The issues https://github.com/modoboa/modoboa/issues/1221 was closed but we get similar issue after modoboa upgrade.

# Impacted versions

* Modoboa: 1.9.0
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce

Configure a user with this passphrase `Des encyclopédistes emmènent les univers.` and try to login with it.

# Current behavior
```
Request Method: | GET
-- | --
1.10.7
UnicodeEncodeError
'ascii' codec can't encode character u'\xe9' in position 58: ordinal not in range(128)
/usr/lib/python2.7/socket.py in meth, line 228
/usr/bin/uwsgi-core
2.7.13
['.',  '',  '/srv/modoboa/env/lib/python2.7',  '/srv/modoboa/env/lib/python2.7/plat-x86_64-linux-gnu',  '/srv/modoboa/env/lib/python2.7/lib-tk',  '/srv/modoboa/env/lib/python2.7/lib-old',  '/srv/modoboa/env/lib/python2.7/lib-dynload',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/srv/modoboa/env/local/lib/python2.7/site-packages',  '/srv/modoboa/env/lib/python2.7/site-packages']
mer, 13 Sep 2017 10:25:06 +0200
```

**Comment by tonioo** [comment] 2017-09-15 08:36
@GreenItSolutions I can't reproduce this issue. Can you provide a complete traceback please?

**Comment by tonioo** [comment] 2017-10-06 16:34
@GreenItSolutions ping

**Comment by GreenItSolutions** [comment] 2017-10-16 15:28
We have test on modoboa without ldap integration. We have the same error.
We'll push here feedback as soon as possible.

**Comment by tonioo** [comment] 2017-12-03 12:53
Fixed in webmail plugin (https://github.com/modoboa/modoboa-webmail/pull/132)

**Closed by tonioo** 2017-12-03 12:53 UTC
Labels: feedback-needed
