### ISSUE TITLE
PDF file for account with mixed langage

### ISSUE THREAD

**Issue by stefaweb** [modoboa/modoboa#1668] opened 2019-02-07 09:44 UTC
DELETED

Problem solved. Was in https://mail/core/#parameters/

**Comment by stefaweb** [comment] 2019-02-07 17:04
Found another problem.

The PDF output is a mix of French and English. I was using French langage in the GUI.

![sc](https://user-images.githubusercontent.com/12907102/52428682-c6fe6300-2b02-11e9-9e32-196cc134f04a.jpg)

**Comment by tonioo** [comment] 2019-02-25 09:17
@stefaweb It is not a bug. The PDF is generated using the target user language. Anyway, I close this issue since it is not the right repository. Please open a new one (https://github.com/modoboa/modoboa-pdfcredentials) if the problem persists.

**Closed by tonioo** 2019-02-25 09:17 UTC
