### ISSUE TITLE
trigger migration from IMAP login?

### ISSUE THREAD

**Issue by fmp777** [modoboa/modoboa#2981] opened 2022-08-20 00:12 UTC
Anyone have some secret sauce to add to dovecot to trigger this auto-create-account + imap migration setup just from an IMAP authentication?  Sure would make automated migrations a lot easier than having to tell each person to login to the web interface

**Comment by tonioo** [comment] 2023-05-09 14:31
I think it could be possible to enable authentication from external IMAP server in dovecot and create a postlogin script to interact with modoboa API.
The only issue I see is the combination of different passdb in dovecot configuration (one for old accounts and one for Modoboa accounts). It is supposed to work but we don't know which passdb matched the authentication in postlogin scripts...

**Comment by Spitfireap** [comment] 2023-08-29 14:56
it seems to be a duplicate of #3004 according to the last comment. We'll try to fix it for a next release :)

**Closed by Spitfireap** 2023-08-29 14:56 UTC
Labels: enhancement, feedback-needed
