### ISSUE TITLE
New version on Github, but not via pip

### ISSUE THREAD

**Issue by yannfill** [modoboa/modoboa#1208] opened 2017-08-01 10:44 UTC
* Modoboa: 1.8.1
* installer used: No
* Webserver: Apache

Modoboa info panel tells me that Modoboa 1.8.2 is available (checked from Github), but 1.8.1 is still the latest version from pip. Since pip install is the recommended way in the documentation, new version availability should be checked from pip, or at least Github and pip milestones should be updated closely.

**Comment by tonioo** [comment] 2017-08-01 11:13
Looks like you have a cache issue because 1.8.2 is available on PyPI (https://pypi.python.org/pypi/modoboa/1.8.2).

**Comment by yannfill** [comment] 2017-08-01 12:02
Strange.
```
# pip search modoboa --no-cache-dir
[...]
modoboa-pdfcredentials (1.1.0)      - Generate PDF documents containing user credentials
  INSTALLED: 1.1.0 (latest)
modoboa-sievefilters (1.1.0)        - The sieve filters editor of Modoboa
  INSTALLED: 1.1.0 (latest)
modoboa (1.8.1)                     - Mail hosting made simple
  INSTALLED: 1.8.1 (latest)
```

**Comment by tonioo** [comment] 2017-08-09 09:03
@yannfill Can you try the following command:
```bash
pip install -vvv modoboa==1.8.2
```
and paste the output please?

**Comment by yannfill** [comment] 2017-08-09 09:54
Last week PyPI only showed Modoboa 1.8.1 https://pypi.python.org/pypi?%3Aaction=search&term=modoboa&submit=search

But using `pip install modoboa==1.8.2` works as expected.

**Comment by tonioo** [comment] 2017-08-09 10:07
Ok. I close the issue since the problem is gone.

**Closed by tonioo** 2017-08-09 10:07 UTC
