### ISSUE TITLE
Dovecot permisson denied error when trying to delete identities

### ISSUE THREAD

**Issue by jcharles-cj** [modoboa/modoboa#2589] opened 2022-08-30 02:52 UTC
`Failed to retrieve mailbox location (b"doveconf: Fatal: Error in configuration file /etc/dovecot/conf.d/10-ssl.conf line 13: ssl_cert: Can't open file /etc/letsencrypt/live/mydomain.com/fullchain.pem: Permission denied\n")`

This is a fresh install of Modoboa and I have tried changing the permissions and error still persists.

System:
Debian 11
Dovecot version: 2.3.13 (89f716dc2)

**Comment by jcharles-cj** [comment] 2022-08-30 03:15
Update: I did this workound and it works now, but is it appropriate?
https://modoboa-wiki.herokuapp.com/en/dovecot-failed-to-retrieve-mailbox-location-error#fix-by-using-commands

**Comment by Spitfireap** [comment] 2022-08-30 06:13
Duplicate of #2570, the relevent PR is here modoboa/modoboa-installer#427 :)

**Closed** 2022-09-05 13:21 UTC

**Comment by ankeshanand1** [comment] 2023-08-04 19:24
I am having the same issue. Any fixes? It was working so far until I tried deleting domain and mailboxes.
```root@mailserver:~# service dovecot status
● dovecot.service - Dovecot IMAP/POP3 email server
     Loaded: loaded (/lib/systemd/system/dovecot.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-08-04 15:16:12 EDT; 7min ago
       Docs: man:dovecot(1)
             http://wiki2.dovecot.org/
   Main PID: 21184 (dovecot)
      Tasks: 6 (limit: 4660)
     Memory: 6.6M
        CPU: 537ms
     CGroup: /system.slice/dovecot.service
             ├─21184 /usr/sbin/dovecot -F
             ├─21187 dovecot/anvil
             ├─21188 dovecot/log
             ├─21189 dovecot/config
             ├─21799 dovecot/stats
             └─21908 dovecot/auth```

**Comment by Spitfireap** [comment] 2023-08-04 19:31
@ankeshanand1 Can you check that `/etc/dovecot/conf.d/10-ssl.conf` contains ``!include_try /etc/dovecot/conf.d/10-ssl-keys.try`` and that `/etc/dovecot/conf.d/10-ssl-keys.try` has 600 permission ?

**Comment by ankeshanand1** [comment] 2023-08-04 20:08
@Spitfireap Here is the error coming from modoboa: `doveconf: Fatal: Error in configuration file /etc/dovecot/conf.d/10-ssl.conf line 52: ssl_cert: Can't open file /etc/letsencrypt/live/server.somehostname.com/fullchain.pem: Permission denied\n`

`10-ssl.conf` does contain `!include_try /etc/dovecot/conf.d/10-ssl-keys.try` but it's commented out and `/etc/dovecot/conf.d/10-ssl-keys.try` is 600.

`10-ssl.conf` config for SSL:
```
ssl_cert = </etc/letsencrypt/live/server.somehostname.com/fullchain.pem
ssl_key = </etc/letsencrypt/live/server.somehostname.com/privkey.pem
```
dovecot is able to start successfully without any permission denied errors but Modoboa shows error when deleting the domains or identities.

**Comment by ankeshanand1** [comment] 2023-08-04 20:13
Surprisingly, I am able to delete new domains that I just added but not the old ones!

**Comment by ankeshanand1** [comment] 2023-08-04 21:31
I logged into vmail user and found out that vmail was infact not able to access /etc/letsencrypt when user owners were dovecot:dovecot whereas it worked fine earlier. Created a new group ssl, added all relevant owners to the group, made vmail the owner of /etc/letsencrypt and all is well now!
