### ISSUE TITLE
Doesn't switch to the faulty tab

### ISSUE THREAD

**Issue by Toniob** [modoboa/modoboa#1370] opened 2018-01-27 10:23 UTC
# Steps to reproduce
Go to parameters and select the Amavis tab. Empty the recipient delimiter field (where a value is required). Don't save and go back to the General tab. Click on save in this tab.

# Current behavior
Nothing happens. You cannot save but nothing is printed and you are not switched to the tab with an error.

# Expected behavior
Switch to the tab with the error or at least, print a message.

**Comment by fresH229a** [comment] 2018-01-27 18:23
Can confirm that too

**Comment by JeroenvO** [comment] 2018-01-27 19:32
Confirm, and same problem with radicale-server adress. A notification is send to the javascript console. 

Errors in saved settings (e.g. 400 returned on 'password' as default password) is not shown to the user either, it is only visible via f12-network by inspecting the ajax response directly.

Probably duplicate of https://github.com/modoboa/modoboa/issues/1371

**Closed** 2018-01-31 12:16 UTC
Labels: bug
