### ISSUE TITLE
noisy cron job handle_mailbox_operations

### ISSUE THREAD

**Issue by helgew** [modoboa/modoboa#1148] opened 2017-06-21 15:27 UTC
Below is the more structured problem description. I had my struggles with this install on a clean CentOS 7 VPS, which I'll post a couple more issues about.

# Impacted versions

* Modoboa: 1.7.4
* installer used: Yes
* Webserver: Apache

# Steps to reproduce

create a fresh install and wait 20 min.

# Current behavior

every 20 min. the handle_mailbox_operations cron job produces the following error:

```python
Traceback (most recent call last):
 File "/srv/modoboa/instance/manage.py", line 22, in <module>
   execute_from_command_line(sys.argv)
 File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
   utility.execute()
 File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
   self.fetch_command(subcommand).run_from_argv(self.argv)
 File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
   self.execute(*args, **cmd_options)
 File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
   output = self.handle(*args, **options)
 File "/srv/modoboa/env/lib/python2.7/site-packages/modoboa/admin/management/commands/handle_mailbox_operations.py", line 105, in handle
   os.unlink(options["pidfile"])
OSError: [Errno 2] No such file or directory: '/tmp/handle_mailbox_operations.pid'
```

# Expected behavior

no error is thrown

**Comment by tonioo** [comment] 2017-12-07 11:09
Can't reproduce this issue, closing for now.

**Closed by tonioo** 2017-12-07 11:09 UTC

**Comment by KarlBaumann** [comment] 2019-11-20 16:58
I am having exactly this issue on latest Modoboa version

**Comment by tonioo** [comment] 2019-11-22 13:59
@KarlBaumann Does it happen every time the task run?

**Comment by KarlBaumann** [comment] 2019-11-22 14:28
Yes. I get this two times every minute
