### ISSUE TITLE
Failed to decode some part of the version of modoboa

### ISSUE THREAD

**Issue by n3witalia** [modoboa/modoboa#3188] opened 2024-02-10 17:58 UTC
# Impacted versions

* OS Type: Debian/Ubuntu
* OS Version: Number or Name
* Database Type: PostgreSQL / MySQL
* Database version: postegres
* Modoboa: last version
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Generating new certificate using letsencrypt
Installing amavis
Installing spamassassin
Installing razor
Installing clamav
Installing fail2ban
Installing modoboa
User modoboa already exists, skipping creation but please make sure the /srv/modoboa directory exists.
Failed to decode some part of the version of modoboa
Failed to decode some part of the version of modoboa
Traceback (most recent call last):
  File "./run.py", line 282, in <module>
    main(sys.argv[1:])
  File "./run.py", line 266, in main
    scripts.install(appname, config, args.upgrade, args.restore)
  File "/root/modoboa-installer/modoboa_installer/scripts/__init__.py", line 29, in install
    getattr(script, appname.capitalize())(config, upgrade, archive_path).run()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 205, in run
    self.install_config_files()
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 158, in install_config_files
    config_files = self.get_config_files()
  File "/root/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 229, in get_config_files
    if self.modoboa_2_2_or_greater:
  File "/root/modoboa-installer/modoboa_installer/scripts/base.py", line 55, in modoboa_2_2_or_greater
    (int(modoboa_version[0]) == 2 and int(modoboa_version[1]) >= 2) or
ValueError: invalid literal for int() with base 10: ' modoboa'
![Screenshot 2024-02-10 185743](https://github.com/modoboa/modoboa/assets/574432/956fbc53-16b4-44b8-adf1-e049e94a8dc2)

# Current behavior

# Expected behavior

# Video/Screenshot link (optional)

**Comment by Gecko64** [comment] 2024-03-04 17:24
I meet the same problem actually and haven't yet found why.
I'm new on Modoboa...

**Comment by SweetBabyCheesus** [comment] 2024-03-17 10:26
I have the same problem, any other fixes than restoring the VM?

**Comment by damko** [comment] 2024-03-29 15:51
I have the same problem.
I'm currently on version 2.1.2, trying to update to the latest version. I've updated the installer at the latest version of today.

**Comment by joyma** [comment] 2024-04-05 12:24
It's caused by unexpected output at the start of "pip show modoboa". The script is relying on the version of modoboa to be in the second line of the output. In my case it was a locale that didn't exist causing a warning at the start of pip show. After running "sudo dpkg-reconfigure locales" and adding the missing locale, the issue was resolved.

**Comment by tonioo** [comment] 2024-04-09 11:03
Fixed by this commit: https://github.com/modoboa/modoboa-installer/commit/9eda3b81bed65c0e4277c1276dbd7df14012a051.

Thanks for the report

**Closed by tonioo** 2024-04-09 11:03 UTC
