### ISSUE TITLE
Domain DKIM don't sign mail

### ISSUE THREAD

**Issue by Orminor77** [modoboa/modoboa#2208] opened 2021-03-29 17:14 UTC
Hello everyone,

I don't think i'm the only one to have this issue.
When I do all the configuration for domain and the DKIM box it's green, my mail don't pass dkim on gmail or other webmail, can someone help me to fix that please, i read some articles about openDKIM on mobodoa website or github but don't work for me, or I fail somewhere.

Thanks in advance for your answer.

**Comment by ynkwave** [comment] 2021-04-01 08:47
Same issue for me, DKIM configuration is fine but all of my mails are not signed..

**Comment by Orminor77** [comment] 2021-04-01 17:34
> Same issue for me, DKIM configuration is fine but all of my mails are not signed..

I could see that Modoboa uses Amavis to sign mails but only locally, I don't understand the interest, there is surely a configuration to do with openDKIM which is also provided with the Modoboa installer. I also tried to install via CentOS 7, Debian 9-10 and Ubuntu 18.04-20.04 but still the same problem. I'm out of ideas.

**Comment by tonioo** [comment] 2021-04-02 08:14
If you used the installer, then OpenDKIM should be installed to sign emails. If you did a manual setup, then you need to install either OpenDKIM or configure amavis to sign emails.

**Comment by yigitkeremoktay** [comment] 2021-04-05 11:34
> If you used the installer, then OpenDKIM should be installed to sign emails. If you did a manual setup, then you need to install either OpenDKIM or configure amavis to sign emails.

I did use the installer and yet, still does not sign emails.

**Comment by tonioo** [comment] 2021-04-06 08:15
@yigitkeremoktay Do you see something in logs?

**Comment by Orminor77** [comment] 2021-04-06 08:18
> If you used the installer, then OpenDKIM should be installed to sign emails. If you did a manual setup, then you need to install either OpenDKIM or configure amavis to sign emails.

Personally I just used the quick installer and I also followed the tutorials of "Linuxbabe" on Debian, Ubuntu and Centos but on all three the mails do not sign

**Comment by yigitkeremoktay** [comment] 2021-04-06 08:20
> @yigitkeremoktay Do you see something in logs?

Is there a specific log that I should check?

**Comment by tonioo** [comment] 2021-04-06 08:58
/var/log/mail.log

**Comment by Orminor77** [comment] 2021-04-07 17:04
> > If you used the installer, then OpenDKIM should be installed to sign emails. If you did a manual setup, then you need to install either OpenDKIM or configure amavis to sign emails.
> 
> Personally I just used the quick installer and I also followed the tutorials of "Linuxbabe" on Debian, Ubuntu and Centos but on all three the mails do not sign

@tonioo Hello, do you have an idea of the issue?

**Comment by yigitkeremoktay** [comment] 2021-04-08 07:53
> /var/log/mail.log

I don't see anything suspcious but there is this

> Apr  8 09:50:54 hostname opendkim[1078]: 2A7F2604F9: no signing table match for 'sender-from@another-domain.com'
> Apr  8 09:50:54 hostname opendkim[1078]: 2A7F2604F9: no signature data

but there is nothing for our accounts, the ones hosted on our mail server

**Comment by tonioo** [comment] 2021-04-09 07:03
Can you check the content of the ``dkim`` view in your database?

**Comment by Orminor77** [comment] 2021-04-09 10:20
> Can you check the content of the `dkim` view in your database?

How to do that? please

**Comment by yigitkeremoktay** [comment] 2021-04-10 09:35
<img width="1022" alt="Screen Shot 2021-04-10 at 12 34 16" src="https://user-images.githubusercontent.com/63040646/114265367-11d4d780-99f9-11eb-9f46-b76b182c9a04.png">
and I can confirm that that file is containing an RSA Key.

**Comment by mattg66** [comment] 2021-04-11 00:28
Same issue here, installer installed 1.17.0

**Comment by rheinon** [comment] 2021-04-11 01:46
Same here.  Fresh install on Debian 10.9.  Dkim key is installed in DNS.  SPF all looks good.  Email test score: 9/10.  1 point loss is from DKIM not signing.

**Postfix version:**
root@mail:~# postconf mail_version
mail_version = 3.4.14

**Opendkim is running:**
~# systemctl status opendkim
Apr 10 18:29:22 mail.domain.com systemd[1]: Starting OpenDKIM DomainKeys Identified Mail (DKIM) Milter...
Apr 10 18:29:22 mail.domain.com systemd[1]: Started OpenDKIM DomainKeys Identified Mail (DKIM) Milter.
Apr 10 18:29:22 mail.domain.com opendkim[14258]: OpenDKIM Filter v2.11.0 starting (args: -x /etc/opendkim.conf)

**/var/lib/dkim/domain.com.pem**
Permission = 600, Owner =opendkim, private key looks good

**/etc/default/opendkim:**
RUNDIR=/var/run/opendkim
USER=opendkim
GROUP=opendkim
PIDFILE=$RUNDIR/$NAME.pid
EXTRAAFTER=
SOCKET="inet:12345@localhost"    # no effect if taking out the quotes or making it 127.0.0.1

**/etc/postfix/main.cf:**
smtpd_milters = inet:127.0.0.1:12345
non_smtpd_milters = inet:127.0.0.1:12345
milter_default_action = accept
milter_content_timeout = 30s

**/etc/opendkim.conf:**
KeyTable		dsn:mysql://opendkim:vdRdiOWDEY9fjoFG@127.0.0.1/modoboa/table=dkim?keycol=id?datacol=domain_name,selector,private_key_path
SigningTable		dsn:mysql://opendkim:vdRdiOWDEY9fjoFG@127.0.0.1/modoboa/table=dkim?keycol=domain_name?datacol=id
Socket                  inet:12345@localhost
PidFile               /var/run/opendkim/opendkim.pid
ExternalIgnoreList      /etc/opendkim.hosts
InternalHosts           /etc/opendkim.hosts

**/etc/opendkim.hosts:**
127.0.0.1
::1
localhost

**/run/opendkim/opendkim.pid**
Owner is root:root.  No effect if changing it to opendkim:opendkim

**MariaDB [modoboa]> select * from dkim;**
![image](https://user-images.githubusercontent.com/55107720/114289337-e8816f00-9a2b-11eb-9ec9-6c0210f96923.png)

**Comment by jefffryfry** [comment] 2021-04-15 14:07
I can confirm same behavior.  emails not signing.  ran quick installer.

**Comment by camodebw** [comment] 2021-04-16 05:59
I can confirm the same issue. Outgoing Emails are not DKIM signed.

Auto Installer runs fine, DKIM Key is generated.

In the mail.log I can't see any opendkim error.

**Comment by walfloresh** [comment] 2021-04-20 01:52
Same exact issue, fresh modoboa 1.17 install on Debian 10, DKIM is generated correctly from GUI, configured on DNS, DKIM Key is present on mysql db but opendkim is not signing any outgoing email. No dkim errors on mail.log whatsoever.

Any advice?

**Comment by dev-mg** [comment] 2021-04-20 13:12
I just had the same problem on Ubuntu 20.4 and fixed it that way: 

- In /etc/postfix/master.cf search for:

```
# Amavis return path
#
127.0.0.1:10025 inet n    -       n       -       -     smtpd
(...)
        -o receive_override_options=no_header_body_checks,no_unknown_recipient_checks,no_milters
```

- Remove no_milters
- Restart postfix

Works fine now :)

**Comment by rheinon** [comment] 2021-04-20 17:07
> I just had the same problem on Ubuntu 20.4 and fixed it that way:
> 
> * In /etc/postfix/master.cf search for:
> 
> ```
> # Amavis return path
> #
> 127.0.0.1:10025 inet n    -       n       -       -     smtpd
> (...)
>         -o receive_override_options=no_header_body_checks,no_unknown_recipient_checks,no_milters
> ```
> 
> * Remove no_milters
> * Restart postfix
> 
> Works fine now :)

I can confirm this works with Debian 10 as well.  Great work!

**Comment by ynkwave** [comment] 2021-04-20 18:25
I will try this

**Comment by Orminor77** [comment] 2021-04-20 20:17
Thanks for your time all, its worked for me !

**Comment by mattg66** [comment] 2021-04-20 22:47
Please reopen this issue to ensure it is resolved in the installer @Orminor77

**Comment by Orminor77** [comment] 2021-04-21 19:02
> Please reopen this issue to ensure it is resolved in the installer @Orminor77

Ok no problem ;)

**Comment by mattg66** [comment] 2021-04-22 08:13
This fix does not work on Debian 10, Postfix refuses to send mail after the change.

**Comment by rheinon** [comment] 2021-04-22 23:25
> This fix does not work on Debian 10, Postfix refuses to send mail after the change. Postfix repsonds with a 451 4.7.1

Is that a fresh install?  I got 2 Debian 10.9 setups, fresh install, both working perfectly after the fix.  You might want to post your /etc/postfix/main.cf and check settings against the default setups posted above.

**Comment by tonioo** [comment] 2021-04-23 07:33
I've just fixed the installer: https://github.com/modoboa/modoboa-installer/commit/c9d67250ba76df2ad12d41e23dbe5918531a3ee4.
Thank you for the analysis!

**Comment by slowaways** [comment] 2021-04-30 05:52
> I just had the same problem on Ubuntu 20.4 and fixed it that way:
> 
> * In /etc/postfix/master.cf search for:
> 
> ```
> # Amavis return path
> #
> 127.0.0.1:10025 inet n    -       n       -       -     smtpd
> (...)
>         -o receive_override_options=no_header_body_checks,no_unknown_recipient_checks,no_milters
> ```
> 
> * Remove no_milters
> * Restart postfix
> 
> Works fine now :)

Thanks!
You saved me!

**Comment by mattg66** [comment] 2021-05-21 12:05
> This fix does not work on Debian 10, Postfix refuses to send mail after the change. Postfix repsonds with a 451 4.7.1

This was due to a permissions error on the DKIM keys from server migration.

**Closed** 2021-06-30 11:48 UTC
