### ISSUE TITLE
Auto-reply function broken in Modoboa 2.2.4

### ISSUE THREAD

**Issue by pappastech** [modoboa/modoboa#3276] opened 2024-07-20 13:55 UTC
# Impacted versions: 2.2.4

* OS Type: Debian 12.4
* Database Type: MySQL
* Modoboa: 2.2.4
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
Configure auto-reply for any user and send an e-mail to that user.

# Current behavior

Upon receipt, Modoboa attempts to send an auto-reply e-mail to the wrong e-mail address. If the valid sending e-mail address is name@fromdomain.com and the valid receipient e-mail address is name@todomain.com, Modoboa attempts to send an e-mail to ("name@todomain.com"@autoreply.todomain.com), double quotes included. Log excerpt below...real hostnames and e-mail address have been altered.

`2024-07-20T08:45:31.052722-05:00 emailhost postfix/postscreen[1133178]: CONNECT from [::1]:56778 to [::1]:25
2024-07-20T08:45:31.053035-05:00 emailhost postfix/postscreen[1133178]: PASS OLD [::1]:56778
2024-07-20T08:45:31.053275-05:00 emailhost postfix/smtpd[1133179]: connect from localhost[::1]
2024-07-20T08:45:31.069508-05:00 emailhost postfix/smtpd[1133179]: NOQUEUE: reject: RCPT from localhost[::1]: 554 5.7.1 <name@fromdomain.com>: Relay access denied; from=<name@todomain.com> to=<name@fromdomain.com> proto=ESMTP helo=<emailhost.todomain.com>
2024-07-20T08:45:31.069594-05:00 emailhost postfix/smtpd[1133179]: using backwards-compatible default setting smtpd_relay_before_recipient_restrictions=no to reject recipient "name@fromdomain.com" from client "localhost[::1]"
2024-07-20T08:45:31.074711-05:00 emailhost postfix/smtpd[1133179]: lost connection after RSET from localhost[::1]
2024-07-20T08:45:31.074807-05:00 emailhost postfix/smtpd[1133179]: disconnect from localhost[::1] ehlo=1 mail=1 rcpt=0/1 rset=1 commands=3/4
2024-07-20T08:45:31.569327-05:00 emailhost postfix/pipe[1133203]: 22C0880418: to=<"name@todomain.com"@autoreply.todomain.com>, orig_to=<name@todomain.com>, relay=autoreply, delay=2.4, delays=0.15/0.03/0/2.3, dsn=5.3.0, status=bounced (Command died with status 1: "/srv/modoboa/env/bin/python")`

# Expected behavior

It's expected that the auto-reply function should work and send a reply to name@fromdomain.com.

**Comment by Spitfireap** [comment] 2024-07-22 13:10
Hi,

2.3.0 version is short of being released, I cannot reproduce the issue with the beta build.
I'm closing the issue for now. Feel free to open it again after 2.3.0 if the issue is not solved on your side.

**Closed by Spitfireap** 2024-07-22 13:10 UTC
