### ISSUE TITLE
Modoboa no longer receiving email, only sending.....

### ISSUE THREAD

**Issue by aaronesteban1** [modoboa/modoboa#2075] opened 2020-10-29 15:43 UTC
# Impacted versions

* Modoboa: LATEST version
* installer used: Yes, via the command line.
* Webserver: Nginx

# Steps to reproduce
I installed Mautic over Modoboa.

# Current behavior
Not able to receive email messages, only able to send.

I was once able to receive messages prior to installing Mautic, but now, I'm no longer able to.
Where is the error log that I can use to find what may be causing this issue? I'm thinking that maybe one of the anti-virus applications stopped working after I did the Mautic installation. Maybe I can look up in the logs to see what stopped working to receive messages. Does anyone know what may be causing this?

Any support is greatly appreciated. Thank you.

**Comment by MrGeneration** [comment] 2020-10-29 21:26
This is a duplicate of https://github.com/modoboa/modoboa/issues/2035
At least does it cover the same topic.

**Comment by kryskool** [comment] 2020-10-30 08:19
Hi @aaronesteban1 

Please check **mail.log**, and i don't know Mautic, but i think it broke your Postfix installation or maybe the database access.

Can you paste some portion of log here

Regards,

**Closed** 2020-12-04 08:58 UTC
Labels: help-needed, question
