### ISSUE TITLE
Not able to save Parameters

### ISSUE THREAD

**Issue by fresH229a** [modoboa/modoboa#1371] opened 2018-01-27 18:16 UTC
# Impacted versions

* Modoboa: 1.10.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
New setup, after login and password change, I am not able to save parameter settings. Nothing happend on pressing SAVE button

**Comment by JeroenvO** [comment] 2018-01-27 19:21
Same problem here. Console output after click on 'save' is:
 An invalid form control with name='modoboa_amavis-recipient_delimiter' is not focusable.

Using modoboa 1.10.1 with amavis, dmarc, statistics, webmail and radicale (all latest version), nginx.

**Comment by fyfe** [comment] 2018-01-27 23:34
duplicate of #1370

**Closed by fyfe** 2018-01-27 23:34 UTC
Labels: bug, duplicate
