### ISSUE TITLE
letsencrypt nginx plugin missing

### ISSUE THREAD

**Issue by donvito-pl** [modoboa/modoboa#2129] opened 2021-01-18 23:22 UTC
# Impacted versions

* OS Type: Debian
* OS Version: Debian 10 Bullseye
* Database Type: PostgreSQL
* Database version: X.y
* Modoboa: X.X.x
* installer used: Yes ?
* Webserver: Nginx

# Steps to reproduce
With letsencrypt enabled and default install certs cannot be renewed due to lack of nginx plugin.

# Current behavior
(..) produced an unexpected error: The requested nginx plugin does not appear to be installed. Skipping.

# Expected behavior
automatic renewal

# Possible Solution
apt-get install python3-certbot-nginx
apt-get install python-certbot-nginx
Adding relevant packages in the installer config file.

**Comment by Meseira** [comment] 2021-02-08 11:33
I get the same thing with Debian Buster. Installing package python3-certbot-nginx is enough to solve it.

However, the plugin cannot find the nginx binary because the default PATH variable is only set to "/usr/bin:/bin" by cron. This is solved by adding the following line at the start of the file "/etc/cron.d/letsencrypt":

`PATH=/usr/sbin:/usr/bin:/sbin:/bin`

**Comment by Meseira** [comment] 2021-02-09 13:16
Moreover, nginx has to be restarted manually with `systemctl restart nginx.service` to take into account the new certificate. I thought the nginx plugin would reload the configuration but something is wrong.

**Comment by ossimantylahti** [comment] 2021-05-01 20:05
I can confirm that this issue is open and valid in Ubuntu 18.04 LTS. Manually installing `sudo apt-get install -y python3-certbot-nginx` and then running `sudo certbot renew` fixes the problem. What remains is to automatize this process.

**Comment by mas1701** [comment] 2021-05-16 00:56
On a fresh install using Debian 10, the nginx plugin of certbot is missing also. As for the automatic renewal set-up in cron, they exist twice: Once in /etc/cron.d/letsencrypt (not working, as described above), once in /etc/cron.d/certbot . The latter is provided by Debian and should work fine.

As for the content of /etc/cron.d/letsencrypt, it runs certbot with --no-self-upgrade - that however is for certbot-auto ONLY, not for regular certbot that is maintained by the Linux distribution as in Debian 10. Also, --force-renewal is a bad idea, it renews the certificate every time the cron job is executed, which is every 12 hours as preconfigured on my fresh Modoboa install. Imagine the stress on Let's Encrypt's signing server if everyone who uses Let's Encrypt did this!

**Comment by ksaadDE** [comment] 2022-06-27 17:41
> On a fresh install using Debian 10, the nginx plugin of certbot is missing also. As for the automatic renewal set-up in cron, they exist twice: Once in /etc/cron.d/letsencrypt (not working, as described above), once in /etc/cron.d/certbot . The latter is provided by Debian and should work fine.
> 
> As for the content of /etc/cron.d/letsencrypt, it runs certbot with --no-self-upgrade - that however is for certbot-auto ONLY, not for regular certbot that is maintained by the Linux distribution as in Debian 10. Also, --force-renewal is a bad idea, it renews the certificate every time the cron job is executed, which is every 12 hours as preconfigured on my fresh Modoboa install. Imagine the stress on Let's Encrypt's signing server if everyone who uses Let's Encrypt did this!

Yes I had the --force-renewal issue as well. I removed it manually in /etc/cron.d/certbot or /etc/cron.d/letsencrypt
I will poke around to remove that setting in the future. However, this is not directly related to this issue, please open a new one for that particular issue.

The last time I installed modoboa, which is a few weeks ago, I had no issues related to  python3-certbot-nginx. Therefore I would like to close this if @tonioo  agrees. 

Regards

**Closed** 2022-06-28 16:42 UTC
Labels: enhancement

**Comment by ksaadDE** [comment] 2022-09-13 21:57
@tonioo  got info in discord, that someone had that issue again, so I fixed this really quick by adding it to requirements.
