### ISSUE TITLE
Cant release Mails

### ISSUE THREAD

**Issue by fresH229a** [modoboa/modoboa#1857] opened 2020-03-19 22:34 UTC
# Impacted versions

* Modoboa: 1.14.0
* installer used: Yes
* Webserver: Nginx

I did a refresh of my server.
Reinstalled modoboa with the installer without errors but I am not able to release any mails now.

Directly in the console I am able to relase it.

Everything else is working fine except the mail releasing.

What can I do or in which logs can I search for the failure?

**Comment by xeeshan-Mustafa** [comment] 2020-05-20 01:15
change the file lib.py on given below path 
/srv/modoboa/env/lib/python3.6/site-packages/modoboa_amavis

**Comment by xeeshan-Mustafa** [comment] 2020-05-20 01:17
[lib.txt](https://github.com/modoboa/modoboa/files/4654071/lib.txt)

**Comment by xeeshan-Mustafa** [comment] 2020-05-20 01:18
change this file extension to lib.txt work for 1.14.0

**Comment by MrGeneration** [comment] 2020-05-20 07:39
Looks like a duplicate of https://github.com/modoboa/modoboa-amavis/issues/119 which is fixed in 1.15.

If possible upgrading to latest modoboa version the issue should be fixed as well.

**Comment by xeeshan-Mustafa** [comment] 2020-05-20 08:31
issue i s not resolved in 1.15.0

**Comment by xeeshan-Mustafa** [comment] 2020-05-20 08:32
i have recently installed new version but problem is till pending

**Comment by rafiwui** [comment] 2020-06-02 21:26
> issue i s not resolved in 1.15.0

Same problem here.

@xeeshan-Mustafa do you know of a workaround for 1.15.0 because I cant change lib.txt to lib.py because there is only a lib.py or is the fix the other way around?

**Comment by xeeshan-Mustafa** [comment] 2020-06-03 00:12
YesSent from my Huawei phone-------- Original Message --------Subject: Re: [modoboa/modoboa] Cant release Mails (#1857)From: rafiwui To: modoboa/modoboa CC: xeeshan-Mustafa ,Mention 

issue i s not resolved in 1.15.0

Same problem here.
@xeeshan-Mustafa do you know of a workaround for 1.15.0 because I cant change lib.txt to lib.py because there is only a lib.py or is the fix the other way around?

**Comment by xeeshan-Mustafa** [comment] 2020-06-03 00:12
Give me email i send u fileSent from my Huawei phone-------- Original Message --------Subject: Re: [modoboa/modoboa] Cant release Mails (#1857)From: rafiwui To: modoboa/modoboa CC: xeeshan-Mustafa ,Mention 

issue i s not resolved in 1.15.0

Same problem here.
@xeeshan-Mustafa do you know of a workaround for 1.15.0 because I cant change lib.txt to lib.py because there is only a lib.py or is the fix the other way around?

**Comment by xeeshan-Mustafa** [comment] 2020-06-03 02:47
Xeeshan.mustafa@gmail.comSent from my Huawei phone-------- Original Message --------Subject: Re: [modoboa/modoboa] Cant release Mails (#1857)From: rafiwui To: modoboa/modoboa CC: xeeshan-Mustafa ,Mention 

issue i s not resolved in 1.15.0

Same problem here.
@xeeshan-Mustafa do you know of a workaround for 1.15.0 because I cant change lib.txt to lib.py because there is only a lib.py or is the fix the other way around?

**Comment by tonioo** [comment] 2020-06-09 08:02
modoboa-amavis 1.3.1 has been released and it fixes this issue.

**Closed by tonioo** 2020-06-09 08:02 UTC

**Comment by xeeshan-Mustafa** [comment] 2020-06-09 14:19
No it is still in 1.14.0 until unless you replace the lib.py file 

And in 1.15.0 until you replace the views.py file
